# Generated by Django 4.1.5 on 2023-01-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='street',
        ),
    ]
